version: "3"
services:
  front:
    build:
      context: ./Client
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment: 
      apiUrl: http://localhost:5000/

  api:
    build:
      context: ./Server
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ConnectionString: server=sqlserver;database=blog;user id=sa;password=LxfMZq15
      ASPNETCORE_DbType: sqlserver
    depends_on:
      - sqlserver

  sqlserver:
    image: "microsoft/mssql-server-linux:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: LxfMZq15
